### ISSUE TITLE
无法完成依赖安装

### ISSUE THREAD

**Issue by ukhack** [Ucas-HaoranWei/GOT-OCR2.0#12]
toml不能直接用于安装？
conda create以后
我先把numpy和cuda手动补全了
最后卡在

LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
报错如下
 ```shell
Using cached deepspeed-0.12.3.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\zhangrui\AppData\Local\Temp\pip-install-860envvc\deepspeed_60f5d540319b43bcb666290c4b48e1cd\setup.py", line 147, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
                 ^^^^^^^^^^^^^^^
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by fukawachan** [comment]
我遇到了同样的问题，查询后发现原因是windows不支持deepspeed，因此缺少相关文件。改用linux环境后解决问题。

**Comment by Ucas-HaoranWei** [comment]
不训练的话，注释掉deepspeed试试？
