### ISSUE TITLE
pip install 出错，deepseed 安装不上

### ISSUE THREAD

**Issue by domeniczz** [Ucas-HaoranWei/GOT-OCR2.0#122]
我的环境是 Windows 11 23H2，Anaconda 24.5.0

我按照 README 中的步骤执行的以下命令：

```
git clone https://github.com/Ucas-HaoranWei/GOT-OCR2.0.git
cd GOT-OCR2.0/GOT-OCR2.0-master/
conda create -n got python=3.10 -y
conda activate got
pip install -e .
```

但是在 `pip install -e .` 遇到了问题， 命令行报错如下：

"
Collecting deepspeed==0.12.3 (from GOT==0.1.0)
  Using cached deepspeed-0.12.3.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\nadir\AppData\Local\Temp\pip-install-_4dmyen5\deepspeed_08104eab66824a03a43d2cb7c795409a\setup.py", line 147, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"

无法安装 deepseed。
尝试安装 GOT.egg-info 目录下的 requires.txt 中的所有包，报错如下：

"
(got) PS D:\Repository\GOT-OCR2.0\GOT-OCR-2.0-master\GOT.egg-info> conda install --file requires.txt
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: \ warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested timm 0.6.13
  - nothing provides requested tiktoken 0.6.0
  - nothing provides requested peft 0.4.0
  - nothing provides requested httpx 0.24.0
  - nothing provides requested einops-exts 0.0.4
  - nothing provides requested einops 0.6.1
  - nothing provides requested deepspeed 0.12.3
  - nothing provides requested bitsandbytes 0.41.0
  - nothing provides requested accelerate 0.28.0
  - nothing provides requested wandb
  - nothing provides requested torch
  - nothing provides requested shortuuid
  - nothing provides requested opencv-python
  - nothing provides requested albumentations
  - package transformers-4.37.2-py310haa95532_0 requires tokenizers >=0.14,<0.19, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ accelerate 0.28.0  does not exist (perhaps a typo or a missing channel);
├─ albumentations does not exist (perhaps a typo or a missing channel);
├─ bitsandbytes 0.41.0  does not exist (perhaps a typo or a missing channel);
├─ deepspeed 0.12.3  does not exist (perhaps a typo or a missing channel);
├─ einops-exts 0.0.4  does not exist (perhaps a typo or a missing channel);
├─ einops 0.6.1  does not exist (perhaps a typo or a missing channel);
├─ httpx 0.24.0  does not exist (perhaps a typo or a missing channel);
├─ opencv-python does not exist (perhaps a typo or a missing channel);
├─ peft 0.4.0  does not exist (perhaps a typo or a missing channel);
├─ pin-1 is installable and it requires
│  └─ python 3.10.* , which can be installed;
├─ shortuuid does not exist (perhaps a typo or a missing channel);
├─ tiktoken 0.6.0  does not exist (perhaps a typo or a missing channel);
├─ timm 0.6.13  does not exist (perhaps a typo or a missing channel);
├─ tokenizers >=0.15.2  is installable with the potential options
│  ├─ tokenizers [0.15.1|0.19.1] would require
│  │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
│  ├─ tokenizers [0.15.1|0.19.1] would require
│  │  └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
│  ├─ tokenizers [0.15.1|0.19.1] would require
│  │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
│  ├─ tokenizers [0.15.1|0.19.1] would require
│  │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
│  └─ tokenizers 0.19.1, which can be installed;
├─ torch does not exist (perhaps a typo or a missing channel);
├─ transformers 4.37.2  is not installable because there are no viable options
│  ├─ transformers 4.37.2 would require
│  │  └─ tokenizers >=0.14,<0.19  but there are no viable options
│  │     ├─ tokenizers 0.15.1 conflicts with any installable versions previously reported;
│  │     ├─ tokenizers [0.15.1|0.19.1], which cannot be installed (as previously explained);
│  │     ├─ tokenizers [0.15.1|0.19.1], which cannot be installed (as previously explained);
│  │     ├─ tokenizers [0.15.1|0.19.1], which cannot be installed (as previously explained);
│  │     └─ tokenizers [0.15.1|0.19.1], which cannot be installed (as previously explained);
│  ├─ transformers 4.37.2 would require
│  │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
│  ├─ transformers 4.37.2 would require
│  │  └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
│  ├─ transformers 4.37.2 would require
│  │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
│  └─ transformers 4.37.2 would require
│     └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
└─ wandb does not exist (perhaps a typo or a missing channel).
"

尝试安装 pytorch 此后，再运行 `pip install -e .`，仍然遇到上述的问题。

**Comment by Ucas-HaoranWei** [comment]
windows似乎得源码编译wheel

**Comment by taiwanhuachenyu** [comment]
https://blog.csdn.net/Changxing_J/article/details/139789110

**Comment by my36z** [comment]
代码改成deepspeed==0.14.5 可以成功，不需要自己打deepspeed

**Comment by domeniczz** [comment]
> 代码改成deepspeed==0.14.5 可以成功，不需要自己打deepspeed

我将 pyproject.toml 中的 deepspeed 版本改成 0.14.5 后，运行 `pip install -e .` 仍然出现一模一样的报错🤣

**Comment by kapok-cjs** [comment]
楼主，用windows的wsl来安装，比较方便，一下子就搞定了

**Comment by hyp530** [comment]
> 楼主，用windows的wsl来安装，比较方便，一下子就搞定了

我用wsl安装，但有依赖冲突不知道如何解决：ERROR: Cannot install GOT and got==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    torchvision 0.20.1 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.20.0 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.19.1 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.19.0 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.18.1 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.18.0 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.17.2 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.17.1 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.17.0 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.16.2 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.16.1 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.16.0 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.15.2 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.15.1 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.14.1 depends on pillow!=8.3.* and >=5.3.0
    torchvision 0.14.0 depends on pillow!=8.3.* and >=5.3.0
    got 0.1.0 depends on torch
    accelerate 0.28.0 depends on torch>=1.10.0
    deepspeed 0.12.3 depends on torch
    peft 0.4.0 depends on torch>=1.13.0
    timm 0.6.13 depends on torch>=1.7
    torchvision 0.13.1 depends on torch==1.12.1
    got 0.1.0 depends on torch
    accelerate 0.28.0 depends on torch>=1.10.0
    deepspeed 0.12.3 depends on torch
    peft 0.4.0 depends on torch>=1.13.0
    timm 0.6.13 depends on torch>=1.7
    torchvision 0.13.0 depends on torch==1.12.0
    got 0.1.0 depends on torch
    accelerate 0.28.0 depends on torch>=1.10.0
    deepspeed 0.12.3 depends on torch
    peft 0.4.0 depends on torch>=1.13.0
    timm 0.6.13 depends on torch>=1.7
    torchvision 0.12.0 depends on torch==1.11.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

**Comment by ToT-Doctor** [comment]
> > 楼主，用windows的wsl来安装，比较方便，一下子就搞定了
> 
> 我用wsl安装，但有依赖冲突不知道如何解决：ERROR: Cannot install GOT and got==0.1.0 because these package versions have conflicting dependencies.我用wsl安装，但有依赖冲突不知道如何解决：ERROR： Cannot install GOT and got==0.1.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by: 冲突是由以下原因引起的： torchvision 0.20.1 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.20.1 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.20.0 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.20.0 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.19.1 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.19.1 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.19.0 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.19.0 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.18.1 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.18.1 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.18.0 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.18.0 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.17.2 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.17.2 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.17.1 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.17.1 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.17.0 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.17.0 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.16.2 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.16.2 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.16.1 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.16.1 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.16.0 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.16.0 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.15.2 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.15.2 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.15.1 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.15.1 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.14.1 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.14.1 依赖于 Pillow！=8.3.* 和 >=5.3.0 torchvision 0.14.0 depends on pillow!=8.3.* and >=5.3.0TorchVision 0.14.0 依赖于 Pillow！=8.3.* 和 >=5.3.0 got 0.1.0 depends on torch 得到 0.1.0 取决于火把 accelerate 0.28.0 depends on torch>=1.10.0加速 0.28.0 依赖于 torch>=1.10.0 deepspeed 0.12.3 depends on torchDeepSpeed 0.12.3 取决于 Torch peft 0.4.0 depends on torch>=1.13.0PEFT 0.4.0 依赖于 torch>=1.13.0 timm 0.6.13 depends on torch>=1.7TIMM 0.6.13 取决于 torch>=1.7 torchvision 0.13.1 depends on torch==1.12.1torchvision 0.13.1 依赖 torch==1.12.1 got 0.1.0 depends on torch 得到 0.1.0 取决于火把 accelerate 0.28.0 depends on torch>=1.10.0加速 0.28.0 依赖于 torch>=1.10.0 deepspeed 0.12.3 depends on torchDeepSpeed 0.12.3 取决于 Torch peft 0.4.0 depends on torch>=1.13.0PEFT 0.4.0 依赖于 torch>=1.13.0 timm 0.6.13 depends on torch>=1.7TIMM 0.6.13 取决于 torch>=1.7 torchvision 0.13.0 depends on torch==1.12.0torchvision 0.13.0 依赖 torch==1.12.0 got 0.1.0 depends on torch 得到 0.1.0 取决于火把 accelerate 0.28.0 depends on torch>=1.10.0加速 0.28.0 依赖于 torch>=1.10.0 deepspeed 0.12.3 depends on torchDeepSpeed 0.12.3 取决于 Torch peft 0.4.0 depends on torch>=1.13.0PEFT 0.4.0 依赖于 torch>=1.13.0 timm 0.6.13 depends on torch>=1.7TIMM 0.6.13 取决于 torch>=1.7 torchvision 0.12.0 depends on torch==1.11.0torchvision 0.12.0 依赖 torch==1.11.0
> 
> To fix this you could try to:要解决此问题，您可以尝试：
> 
> 1. loosen the range of package versions you've specified放宽您指定的包版本范围
> 2. remove package versions to allow pip to attempt to solve the dependency conflict删除包版本以允许 pip 尝试解决依赖项冲突

不用wsl，直接用别人编译过的deepspeed，这个是python3.10的pip install https://github.com/daswer123/resemble-enhance-windows/releases/download/deepspeed/deepspeed-0.11.2+cuda121-cp310-cp310-win_amd64.whl，记得改文件里deepspeed的版本
