### ISSUE TITLE
训练stage-3，推理时出错：ValueError: Trying to set a tensor of shape torch.Size([0]) in "weight" (which has shape torch.Size([151860, 1024])), this look incorrect.

### ISSUE THREAD

**Issue by yangy272** [Ucas-HaoranWei/GOT-OCR2.0#135]
如题，训练stage-3，训练时正常，推理出现错误：

Traceback (most recent call last):
  File "/root/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/demo/run_ocr_2.0.py", line 245, in <module>
    eval_model(args)
  File "/root/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/demo/run_ocr_2.0.py", line 52, in eval_model
    model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643).eval()
  File "/root/.conda/envs/sft/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3850, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/.conda/envs/sft/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4284, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/root/.conda/envs/sft/lib/python3.10/site-packages/transformers/modeling_utils.py", line 805, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/root/.conda/envs/sft/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 348, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([0]) in "weight" (which has shape torch.Size([151860, 1024])), this look incorrect.

命令如下：
python3 GOT/demo/run_ocr_2.0.py  --model-name  ./GOT-OCR2.0/sft/  --image-file  ./1.jpg  --type ocr

训练结果
![image](https://github.com/user-attachments/assets/f0080db9-1bac-4cfc-911b-6d399b6f3de6)

训练命令：
deepspeed   ./GOT-OCR-2.0-master/GOT/train/train_GOT.py \
 --deepspeed ./GOT-OCR-2.0-master/zero_config/zero3.json    --model_name_or_path ./GOT/model \
 --use_im_start_end True   \
 --fp16 True   \
 --gradient_accumulation_steps 2    \
 --evaluation_strategy "no"   \
 --save_strategy "steps"  \
 --save_steps 200   \
 --save_total_limit 1   \
 --weight_decay 0.    \
 --warmup_ratio 0.001     \
 --lr_scheduler_type "cosine"    \
 --logging_steps 1    \
 --tf32 True     \
 --model_max_length 8192    \
 --gradient_checkpointing True   \
 --dataloader_num_workers 8    \
 --report_to none  \
 --per_device_train_batch_size 8    \
 --num_train_epochs 1  \
 --learning_rate 2e-5   \
 --datasets pdf-ocr \
 --output_dir ./sft

**Comment by Ucas-HaoranWei** [comment]
看起来像weights出问题了，没有lmhead 的weights？

**Comment by yangy272** [comment]
但是训练过程是正常的，所以不知道具体是什么地方出了问题

**Comment by yangy272** [comment]
> 看起来像weights出问题了，没有lmhead 的weights？
但是训练过程是正常的，所以不知道具体是什么地方出了问题

**Comment by Ucas-HaoranWei** [comment]
> > 看起来像weights出问题了，没有lmhead 的weights？
> > 但是训练过程是正常的，所以不知道具体是什么地方出了问题

把你的weights和开源的weights的key 每个v的shape对比下呢？

**Comment by yangy272** [comment]
> > > 看起来像weights出问题了，没有lmhead 的weights？
> > > 但是训练过程是正常的，所以不知道具体是什么地方出了问题
> 
> 把你的weights和开源的weights的key 每个v的shape对比下呢？


那请问train stage-2和train stage-3是不是需要修改代码，我用同样的数据，训练 stage-2就没问题

**Comment by Ucas-HaoranWei** [comment]
这个代码无stage2和stage3之分，你train的都是stage3，
你所谓的stage只不过是deepspeed zero的stage2或者stage3，都是训的got的stage3，你可以看看zero

**Comment by LymanY** [comment]
> > > > 看起来像weights出问题了，没有lmhead 的weights？
> > > > 但是训练过程是正常的，所以不知道具体是什么地方出了问题
> > 
> > 
> > 把你的weights和开源的weights的key 每个v的shape对比下呢？
> 
> 那请问train stage-2和train stage-3是不是需要修改代码，我用同样的数据，训练 stage-2就没问题

same problem
