### ISSUE TITLE
使用ms-swift微调时，transformers库无法正确加载模型。

### ISSUE THREAD

**Issue by amannier** [Ucas-HaoranWei/GOT-OCR2.0#155]
使用ms-swift版本为2.6.0.dev0，transformers库为4.45.2时报错
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/xxx/anaconda3/envs/f_got/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1023, in from_pretrained
[rank1]:     config_class = CONFIG_MAPPING[config_dict["model_type"]]
[rank1]:   File "/home/xxx/anaconda3/envs/f_got/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 725, in __getitem__
[rank1]:     raise KeyError(key)
[rank1]: KeyError: 'GOT'

[rank1]: During handling of the above exception, another exception occurred:

[rank1]: Traceback (most recent call last):
[rank1]:   File "/data/xxx/ms-swift-main/swift/cli/sft.py", line 5, in <module>
[rank1]:     sft_main()
[rank1]:   File "/data/xxx/ms-swift-main/swift/utils/run_utils.py", line 32, in x_main
[rank1]:     result = llm_x(args, **kwargs)
[rank1]:   File "/data/xxx/ms-swift-main/swift/llm/sft.py", line 539, in llm_sft
[rank1]:     model, template, callbacks = prepare_model_template_train(args, msg)
[rank1]:   File "/data/xxx/ms-swift-main/swift/llm/sft.py", line 218, in prepare_model_template_train
[rank1]:     model, tokenizer = get_model_tokenizer(
[rank1]:   File "/data/xxx/ms-swift-main/swift/llm/utils/model.py", line 7146, in get_model_tokenizer
[rank1]:     model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
[rank1]:   File "/data/xxx/ms-swift-main/swift/llm/utils/model.py", line 6987, in get_model_tokenizer_got_ocr2
[rank1]:     model, tokenizer = get_model_tokenizer_with_flash_attn(*args, **kwargs)
[rank1]:   File "/data/xxx/ms-swift-main/swift/llm/utils/model.py", line 2918, in get_model_tokenizer_with_flash_attn
[rank1]:     model_config = AutoConfig.from_pretrained(model_dir, trust_remote_code=True)
[rank1]:   File "/home/xxx/anaconda3/envs/f_got/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1025, in from_pretrained
[rank1]:     raise ValueError(
[rank1]: ValueError: The checkpoint you are trying to load has model type `GOT` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
问题好像是AutoConfig无法从GOT_weights文件夹中的config.json文件中加载config，因为transformers库没有提供GOT的model_type？
用ms-swift微调应该怎么解决这个问题。

**Comment by amannier** [comment]
sh文件如下：
NPROC_PER_NODE=2 \
CUDA_VISIBLE_DEVICES=5,6 swift sft \
--model_type got-ocr2 \
--model_id_or_path '/data/xxx/FullPageOCRTest/GOT-OCR2.0-main/GOT-OCR-2.0-master/GOT_weights' \
--sft_type lora \
--dataset '/home/xxx/finetune/10_22_multimodel/qwen2-ft-compdata.jsonl' \
--deepspeed default-zero2
能有在使用ms-swift微调的条件下从本地而非ModelScope Hub加载GOT的方法吗？

**Comment by Ucas-HaoranWei** [comment]
你把Modelscope的模型下载到本地就行

**Comment by amannier** [comment]
请问transformers应该使用什么版本？我使用的是4.46.0会报错
NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.
