### ISSUE TITLE
The checkpoint you are trying to load has model type `GOT` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

### ISSUE THREAD

**Issue by Charimanhua** [Ucas-HaoranWei/GOT-OCR2.0#161]
代码：
```
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('GOT-OCR2.0/GOT-OCR-2.0-master/GOT/model/GOT_weights', trust_remote_code=True)
model = AutoModel.from_pretrained('GOT-OCR2.0/GOT-OCR-2.0-master/GOT/model/GOT_weights', trust_remote_code=True, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=tokenizer.eos_token_id)
model = model.eval().cuda()


# input your test image
image_file = '/mnt/HDD/Hhr/heishenhua_timeseries/2024-08-27/OueColBBn_1.png'

# plain texts OCR
res = model.chat(tokenizer, image_file, ocr_type='ocr')

# format texts OCR:
# res = model.chat(tokenizer, image_file, ocr_type='format')

# fine-grained OCR:
# res = model.chat(tokenizer, image_file, ocr_type='ocr', ocr_box='')
# res = model.chat(tokenizer, image_file, ocr_type='format', ocr_box='')
# res = model.chat(tokenizer, image_file, ocr_type='ocr', ocr_color='')
# res = model.chat(tokenizer, image_file, ocr_type='format', ocr_color='')

# multi-crop OCR:
# res = model.chat_crop(tokenizer, image_file, ocr_type='ocr')
# res = model.chat_crop(tokenizer, image_file, ocr_type='format')

# render the formatted OCR results:
# res = model.chat(tokenizer, image_file, ocr_type='format', render=True, save_render_file = './demo.html')

print(res)
```

报错：
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1034, in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   [1033](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1033) try:
-> [1034](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1034)     config_class = CONFIG_MAPPING[config_dict["model_type"]]
   [1035](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1035) except KeyError:

File ~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:736, in _LazyConfigMapping.__getitem__(self, key)
    [735](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:735) if key not in self._mapping:
--> [736](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:736)     raise KeyError(key)
    [737](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:737) value = self._mapping[key]

KeyError: 'GOT'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[1], [line 4](vscode-notebook-cell:?execution_count=1&line=4)
      [1](vscode-notebook-cell:?execution_count=1&line=1) from transformers import AutoModel, AutoTokenizer
      [3](vscode-notebook-cell:?execution_count=1&line=3) tokenizer = AutoTokenizer.from_pretrained('/home/user1809/HuahaiRan/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/model/GOT_weights', trust_remote_code=True)
----> [4](vscode-notebook-cell:?execution_count=1&line=4) model = AutoModel.from_pretrained('/home/user1809/HuahaiRan/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/model/GOT_weights', trust_remote_code=True, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=tokenizer.eos_token_id)
      [5](vscode-notebook-cell:?execution_count=1&line=5) model = model.eval().cuda()
      [8](vscode-notebook-cell:?execution_count=1&line=8) # input your test image

File ~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:526, in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
...
   [1042](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1042) else:
   [1043](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1043)     # Fallback: use pattern matching on the string.
   [1044](https://vscode-remote+ssh-002dremote-002bmyhost.vscode-resource.vscode-cdn.net/home/user1809/HuahaiRan/social-memeing-main/memes/mycode/~/anaconda3/envs/meme/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1044)     # We go from longer names to shorter names to catch roberta before bert (for instance)

ValueError: The checkpoint you are trying to load has model type `GOT` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?3b824246-4806-444b-b3f3-de323651366d) or open in a [text editor](command:workbench.action.openLargeOutput?3b824246-4806-444b-b3f3-de323651366d). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
``
```
模型我已经部署到本地了，然后可以使用命令行
python GOT-OCR2.0/GOT-OCR-2.0-master/GOT/demo/run_ocr_2.0.py  --model-name GOT-OCR2.0/GOT-OCR-2.0-master/GOT/model/GOT_weights  --image-file  xxxxx.png  --type ocr
是可以运行模型，识别出文字的。
版本如下：
Name: transformers
Version: 4.37.2
请问该如何解决？

**Comment by Charimanhua** [comment]
已解决，谢谢！

**Comment by Devcode518** [comment]
> 你下载的权重文件夹不匹配啊，你得下载huggingface 的config

大佬你好，我也报了一个关键信息一样的错，我用的谷歌网盘里面那一套文件，然后报这个错，麻烦帮我看一下

  warnings.warn(_BETA_TRANSFORMS_WARNING)
[INFO:swift] Successfully registered `/workspace/ms-swift/swift/llm/data/dataset_info.json`
[INFO:swift] No vLLM installed, if you are using vLLM, you will get `ImportError: cannot import name 'get_vllm_engine' from 'swift.llm'`
[INFO:swift] No LMDeploy installed, if you are using LMDeploy, you will get `ImportError: cannot import name 'prepare_lmdeploy_engine_template' from 'swift.llm'`
[INFO:swift] Start time of running main: 2024-11-20 06:18:00.344620
[INFO:swift] Setting template_type: got_ocr2
[INFO:swift] Setting args.lazy_tokenize: True
[INFO:swift] Setting args.dataloader_num_workers: 1
[INFO:swift] output_dir: /workspace/ms-swift/output/got-ocr2/v0-20241120-061800
[INFO:swift] args: SftArguments(model_type='got-ocr2', model_id_or_path='/workspace/GOT-OCR2.0/GOT-OCR-2.0-master/GOT_weights', model_revision='master', full_determinism=False, sft_type='lora', freeze_parameters=[], freeze_vit=False, freeze_parameters_ratio=0.0, additional_trainable_parameters=[], tuner_backend='peft', template_type='got_ocr2', output_dir='/workspace/ms-swift/output/got-ocr2/v0-20241120-061800', add_output_dir_suffix=True, ddp_backend=None, ddp_find_unused_parameters=None, ddp_broadcast_buffers=None, ddp_timeout=1800, seed=42, resume_from_checkpoint=None, resume_only_model=False, ignore_data_skip=False, dtype='bf16', packing=False, train_backend='transformers', tp=1, pp=1, min_lr=None, sequence_parallel=False, model_kwargs={}, loss_name=None, dataset=['/workspace/GOT-OCR2.0/GOT-OCR-2.0-master/yinzhang/train.json'], val_dataset=[], dataset_seed=42, dataset_test_ratio=0.01, use_loss_scale=False, loss_scale_config_path='/workspace/ms-swift/swift/llm/agent/default_loss_scale_config.json', system=None, tools_prompt='react_en', max_length=2048, truncation_strategy='delete', check_dataset_strategy='none', streaming=False, streaming_val_size=0, streaming_buffer_size=16384, model_name=[None, None], model_author=[None, None], quant_method=None, quantization_bit=0, hqq_axis=0, hqq_dynamic_config_path=None, bnb_4bit_comp_dtype='bf16', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, rescale_image=-1, target_modules='^(model.layers|model.mm_projector_vary)(?!.*(lm_head|output|emb|wte|shared)).*', target_regex=None, modules_to_save=[], lora_rank=8, lora_alpha=32, lora_dropout=0.05, lora_bias_trainable='none', lora_dtype='AUTO', lora_lr_ratio=None, use_rslora=False, use_dora=False, init_lora_weights='true', fourier_n_frequency=2000, fourier_scaling=300.0, rope_scaling=None, boft_block_size=4, boft_block_num=0, boft_n_butterfly_factor=1, boft_dropout=0.0, vera_rank=256, vera_projection_prng_key=0, vera_dropout=0.0, vera_d_initial=0.1, adapter_act='gelu', adapter_length=128, use_galore=False, galore_target_modules=None, galore_rank=128, galore_update_proj_gap=50, galore_scale=1.0, galore_proj_type='std', galore_optim_per_parameter=False, galore_with_embedding=False, galore_quantization=False, galore_proj_quant=False, galore_proj_bits=4, galore_proj_group_size=256, galore_cos_threshold=0.4, galore_gamma_proj=2, galore_queue_size=5, adalora_target_r=8, adalora_init_r=12, adalora_tinit=0, adalora_tfinal=0, adalora_deltaT=1, adalora_beta1=0.85, adalora_beta2=0.85, adalora_orth_reg_weight=0.5, ia3_feedforward_modules=[], llamapro_num_new_blocks=4, llamapro_num_groups=None, neftune_noise_alpha=None, neftune_backend='transformers', lisa_activated_layers=0, lisa_step_interval=20, reft_layer_key=None, reft_layers=None, reft_rank=4, reft_intervention_type='LoreftIntervention', reft_args=None, use_liger=False, gradient_checkpointing=True, vit_use_gc=True, deepspeed=None, batch_size=1, eval_batch_size=1, auto_find_batch_size=False, num_train_epochs=1, max_steps=-1, optim='adamw_torch', adam_beta1=0.9, adam_beta2=0.95, adam_epsilon=1e-08, learning_rate=0.0001, weight_decay=0.1, gradient_accumulation_steps=16, max_grad_norm=1, predict_with_generate=False, lr_scheduler_type='cosine', lr_scheduler_kwargs={}, warmup_ratio=0.05, warmup_steps=0, eval_steps=50, save_steps=50, save_only_model=False, save_total_limit=2, logging_steps=5, acc_steps=1, dataloader_num_workers=1, dataloader_pin_memory=True, dataloader_drop_last=False, push_to_hub=False, hub_model_id=None, hub_token=None, hub_private_repo=False, hub_strategy='every_save', test_oom_error=False, disable_tqdm=False, lazy_tokenize=True, preprocess_num_proc=1, use_flash_attn=None, ignore_args_error=False, check_model_is_latest=True, logging_dir='/workspace/ms-swift/output/got-ocr2/v0-20241120-061800/runs', report_to=['tensorboard'], acc_strategy='token', save_on_each_node=False, evaluation_strategy='steps', save_strategy='steps', save_safetensors=True, gpu_memory_fraction=None, include_num_input_tokens_seen=False, local_repo_path=None, custom_register_path=None, custom_dataset_info=None, device_map_config=None, device_max_memory=[], max_new_tokens=2048, do_sample=None, temperature=None, top_k=None, top_p=None, repetition_penalty=None, num_beams=1, fsdp='', fsdp_config=None, sequence_parallel_size=1, model_layer_cls_name=None, metric_warmup_step=0, fsdp_num=1, per_device_train_batch_size=None, per_device_eval_batch_size=None, eval_strategy=None, self_cognition_sample=0, train_dataset_mix_ratio=0.0, train_dataset_mix_ds=['ms-bench'], train_dataset_sample=-1, val_dataset_sample=None, safe_serialization=None, only_save_model=None, neftune_alpha=None, deepspeed_config_path=None, model_cache_dir=None, lora_dropout_p=None, lora_target_modules=[], lora_target_regex=None, lora_modules_to_save=[], boft_target_modules=[], boft_modules_to_save=[], vera_target_modules=[], vera_modules_to_save=[], ia3_target_modules=[], ia3_modules_to_save=[], custom_train_dataset_path=[], custom_val_dataset_path=[], device_map_config_path=None, push_hub_strategy=None)
[INFO:swift] Global seed set to 42
device_count: 1
rank: -1, local_rank: -1, world_size: 1, local_world_size: 1
[INFO:swift] Loading the model using model_dir: /workspace/GOT-OCR2.0/GOT-OCR-2.0-master/GOT_weights
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1034, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 736, in __getitem__
    raise KeyError(key)
KeyError: 'GOT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/ms-swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/workspace/ms-swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/workspace/ms-swift/swift/llm/sft.py", line 544, in llm_sft
    model, template, callbacks = prepare_model_template_train(args, msg)
  File "/workspace/ms-swift/swift/llm/sft.py", line 218, in prepare_model_template_train
    model, tokenizer = get_model_tokenizer(
  File "/workspace/ms-swift/swift/llm/utils/model.py", line 7265, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/workspace/ms-swift/swift/llm/utils/model.py", line 7106, in get_model_tokenizer_got_ocr2
    model, tokenizer = get_model_tokenizer_with_flash_attn(*args, **kwargs)
  File "/workspace/ms-swift/swift/llm/utils/model.py", line 2989, in get_model_tokenizer_with_flash_attn
    model_config = AutoConfig.from_pretrained(model_dir, trust_remote_code=True)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1036, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `GOT` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

非常感谢！

**Comment by nilaan-effectz** [comment]
encountered the same issue , i used the weights i donwloaded from google drive 

do you mean i need to to provide the model id and let it automatically download from hugging face . ( this download take too much time ) 

1. in huggingface also the model_type is GOT 

![Image](https://github.com/user-attachments/assets/08d341c1-4e0b-45c4-9ff9-36fcb860d52a)
