### ISSUE TITLE
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.

### ISSUE THREAD

**Issue by wjm030612** [Ucas-HaoranWei/GOT-OCR2.0#163]
我在linux服务器上运行时候，有这个报错，精度不符合，我改了他说的`/root/.cache/huggingface/modules/transformers_modules/GOT-OCR2_0/modeling_GOT.py", line 581,`但是还是会自动变为bf16，我的显卡是4张TiTanV，cuda版本的12.1，已经困扰我一个星期了，请问能帮我解决下吗，错误提示和代码都附上了
> To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2364, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 864, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/fuwu1.py", line 13, in perform_ocr
    res = model.chat(tokenizers, image_file, ocr_type='ocr')
  File "/root/.cache/huggingface/modules/transformers_modules/GOT-OCR2_0/modeling_GOT.py", line 581, in chat
    with torch.autocast("cuda", dtype=torch.bfloat16):
  File "/opt/conda/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 305, in __init__
    raise RuntimeError(
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.

```
import gradio as gr
from transformers import AutoModel, AutoTokenizer
import torch
# Load the tokenizer and model
tokenizers = AutoTokenizer.from_pretrained(r'/workspace/GOT-OCR2_0', trust_remote_code=True)
model = AutoModel.from_pretrained(r'/workspace/GOT-OCR2_0', trust_remote_code=True,
                                  low_cpu_mem_usage=True, device_map='cuda',
                                  use_safetensors=True)
model = model.eval().cuda()

def perform_ocr(image_file):
    torch.set_default_dtype(torch.float16)
    res = model.chat(tokenizers, image_file, ocr_type='ocr')
    return res


iface = gr.Interface(
    fn=perform_ocr,
    inputs=gr.Image(type="filepath"),
    outputs="text",
    title="OCR",
    description="Upload",
)

iface.launch(server_name='0.0.0.0', server_port=8808)
```

**Comment by 450711420** [comment]
chat里的dtype全部改成float16就好了

**Comment by wjm030612** [comment]
在下载的hugging face权重的文件夹里面，有个modeling_got，在这里面改了就行了

**Comment by HsiangLeekwok** [comment]
> 在下载的hugging face权重的文件夹里面，有个modeling_got，在这里面改了就行了

@wjm030612 改了没用，再次运行会被重新覆盖成bfloat16，一样报错

**Comment by lifejwang11** [comment]
> > 在下载的hugging face权重的文件夹里面，有个modeling_got，在这里面改了就行了
> 
> @wjm030612 改了没用，再次运行会被重新覆盖成bfloat16，一样报错

估计你重新下载覆盖了，我改了是可以的

**Comment by HsiangLeekwok** [comment]
> > > 在下载的hugging face权重的文件夹里面，有个modeling_got，在这里面改了就行了
> > 
> > 
> > @wjm030612 改了没用，再次运行会被重新覆盖成bfloat16，一样报错
> 
> 估计你重新下载覆盖了，我改了是可以的

不是，没重新下载。是我当时改错地方了，不应该改 `/root/.cache/huggingface/modules/transformers_modules/GOT-OCR2_0/modeling_GOT.py` 里的，这个文件每次运行都会被覆盖，应该改自己 clone 下来的文件夹下面的 modeling_got.py 才对。

**Comment by lifejwang11** [comment]
> > > > 在下载的hugging face权重的文件夹里面，有个modeling_got，在这里面改了就行了
> > > 
> > > 
> > > @wjm030612 改了没用，再次运行会被重新覆盖成bfloat16，一样报错
> > 
> > 
> > 估计你重新下载覆盖了，我改了是可以的
> 
> 不是，没重新下载。是我当时改错地方了，不应该改 `/root/.cache/huggingface/modules/transformers_modules/GOT-OCR2_0/modeling_GOT.py` 里的，这个文件每次运行都会被覆盖，应该改自己 clone 下来的文件夹下面的 modeling_got.py 才对。

每个下载都有缓存标识的，你给删除了吧，他重新下载了，一般有不回重新下载的
