### ISSUE TITLE
调用 run_ocr_2.0 默认的模型 facebook/opt-350m 在运行到加载模型步骤的时候为什么会报错？

### ISSUE THREAD

**Issue by jjjason95** [Ucas-HaoranWei/GOT-OCR2.0#17]
调用 run_ocr_2.0 默认的模型 facebook/opt-350m 在运行到加载模型步骤的时候为什么会报错？

报错信息如下：

`Traceback (most recent call last):
  File "/app/repos/vary/GOT/demo/run_ocr_2.0.py", line 244, in <module>
    eval_model(args)
  File "/app/repos/vary/GOT/demo/run_ocr_2.0.py", line 51, in eval_model
    model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643).eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3594, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/repos/vary/GOT/model/GOT_ocr_2_0.py", line 214, in __init__
    self.model = GOTQwenModel(config)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/app/repos/vary/GOT/model/GOT_ocr_2_0.py", line 23, in __init__
    super(GOTQwenModel, self).__init__(config)
  File "/root/miniconda3/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 930, in __init__
    self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 133, in __init__
    assert padding_idx < self.num_embeddings, 'Padding_idx must be within num_embeddings'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Padding_idx must be within num_embeddings`

**Comment by jjjason95** [comment]
不好意思，选错了模型

**Comment by goldeneave** [comment]
我也是用的默认的模型，也报了同样的错，想请教一下后来怎么解决的
