### ISSUE TITLE
出错：neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by yibie** [Ucas-HaoranWei/GOT-OCR2.0#29]
按照 Readme 进行安装，但运行 pip install -e . 后出现这个错误提示。

我检查了项目所在路径，确实没有找到这两个文件。

**Comment by SamuraiBUPT** [comment]
cd 到 GOT-OCR-2.0-master 再安装

**Comment by yibie** [comment]
Ok 了，谢谢！

**Comment by yibie** [comment]
现在我切换到 Conda 全新的环境下，运行 pip install -e . 出现如下错误：

reparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/setup.py", line 38, in <module>
          from op_builder.all_ops import ALL_OPS
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/op_builder/all_ops.py", line 29, in <module>
          builder = get_accelerator().create_op_builder(member_name)
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/accelerator/mps_accelerator.py", line 223, in create_op_builder
          builder_class = self.get_op_builder(op_name)
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/accelerator/mps_accelerator.py", line 230, in get_op_builder
          from deepspeed.ops.op_builder.cpu import NotImplementedBuilder
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/__init__.py", line 21, in <module>
          from . import ops
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/ops/__init__.py", line 6, in <module>
          from . import adam
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/ops/adam/__init__.py", line 6, in <module>
          from .cpu_adam import DeepSpeedCPUAdam
        File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/ops/adam/cpu_adam.py", line 7, in <module>
          from cpuinfo import get_cpu_info
      ModuleNotFoundError: No module named 'cpuinfo'
      [end of output]

**Comment by Maple0709** [comment]
> Ok 了，谢谢！

请问安装成功了吗？我按照要求，cd 到 GOT-OCR-2.0-master 再安装，出现了以下错误：
ERROR: Project file:///app/GOT-OCR-2.0-master has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
root@6e67a675da78:/app/GOT-OCR-2.0-master# pip3 install -e .
Obtaining file:///app/GOT-OCR-2.0-master
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///app/GOT-OCR-2.0-master has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

**Comment by robot010** [comment]
跑一下 `pip install py-cpuinfo` 就可以解决 ModuleNotFoundError: No module named 'cpuinfo'的问题了。
