### ISSUE TITLE
出错：在全新的 conda 虚拟环境下安装出现报错

### ISSUE THREAD

**Issue by yibie** [Ucas-HaoranWei/GOT-OCR2.0#33]
现在我切换到 Conda 全新的环境下，运行 pip install -e . 出现如下错误：

reparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [20 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/setup.py", line 38, in
from op_builder.all_ops import ALL_OPS
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/op_builder/all_ops.py", line 29, in
builder = get_accelerator().create_op_builder(member_name)
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/accelerator/mps_accelerator.py", line 223, in create_op_builder
builder_class = self.get_op_builder(op_name)
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/accelerator/mps_accelerator.py", line 230, in get_op_builder
from deepspeed.ops.op_builder.cpu import NotImplementedBuilder
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/init.py", line 21, in
from . import ops
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/ops/init.py", line 6, in
from . import adam
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/ops/adam/init.py", line 6, in
from .cpu_adam import DeepSpeedCPUAdam
File "/private/var/folders/ns/sfzfbcd16d19rky4mtm4gpbm0000gn/T/pip-install-kh4sm3zu/deepspeed_bc874f9bbb254ac2828ec64473cc4372/deepspeed/ops/adam/cpu_adam.py", line 7, in
from cpuinfo import get_cpu_info
ModuleNotFoundError: No module named 'cpuinfo'
[end of output]

**Comment by Ucas-HaoranWei** [comment]
怎么感觉cd的目录不对，你需要训练吗，inference的话试一下huggingface：https://huggingface.co/ucaslcl/GOT-OCR2_0

**Comment by yibie** [comment]
是的，反馈的目录结构应该是 linux 的，但我用的是 mac。
我在线上试一下看看。

**Comment by robot010** [comment]
跑一下 `pip install py-cpuinfo` 就可以解决 ModuleNotFoundError: No module named 'cpuinfo'的问题了。
