### ISSUE TITLE
安装flash-attn出错

### ISSUE THREAD

**Issue by xiaotangwan** [Ucas-HaoranWei/GOT-OCR2.0#39]
(got) zhujiayi@cup1504-3090:~/study/GOT-OCR2.0$ pip install flash-attn --no-build-isolation
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting flash-attn
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cd/1e/21321670cd3c2f225026d9fd89272cae661529238850e79f48ccf2f9e4e3/flash_attn-2.6.3.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: 不是 git 仓库（或者任何父目录）：.git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_a81xh_b/flash-attn_c1680cdca2584fff8c154a31f689b6de/setup.py", line 160, in <module>
          raise RuntimeError(
      RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.

      torch.__version__  = 2.4.1+cu121

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by woshidama323** [comment]
Same issue

**Comment by woshidama323** [comment]
问题是：
`File "/tmp/pip-install-_a81xh_b/flash-attn_c1680cdca2584fff8c154a31f689b6de/setup.py", line 160, in
raise RuntimeError(
RuntimeError: FlashAttention is only supported on CUDA 11.6 and above. Note: make sure nvcc has a supported version by running nvcc -V.`

nvcc -V 看下如果是11.6以下就重新升级下cuda toolkit 

我这边成功
