### ISSUE TITLE
【求助】执行demo里的run_ocr_2.0.py之后报错

### ISSUE THREAD

**Issue by liutianye** [Ucas-HaoranWei/GOT-OCR2.0#74]
(got) tellyes@tellyes-ThinkSystem-ST650-V2:~/ai_tools/GOT-OCR2.0/GOT-OCR-2.0-master$ CUDA_VISIBLE_DEVICES=1 python3 GOT/demo/run_ocr_2.0.py  --model-name  /GOT_weights/  --image-file  /home/tellyes/ai_tools/nvidia-smi.png  --type ocr
Traceback (most recent call last):
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 49, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tellyes/ai_tools/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/demo/run_ocr_2.0.py", line 8, in <module>
    from GOT.model import *
  File "/home/tellyes/ai_tools/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/model/__init__.py", line 2, in <module>
    from .GOT_ocr_2_0 import GOTQwenModel, GOTQwenForCausalLM, GOTConfig
  File "/home/tellyes/ai_tools/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/model/GOT_ocr_2_0.py", line 1, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, \
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1355, in __getattr__
    value = getattr(module, name)
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1354, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.qwen2.modeling_qwen2 because of the following error (look up to see its traceback):
/home/tellyes/anaconda3/envs/got/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
(got) tellyes@tellyes-ThinkSystem-ST650-V2:~/ai_tools/GOT-OCR2.0/GOT-OCR-2.0-master$

按readme执行，我随便找了个图片放服务器里，然后执行了demo语句，报了这两个错误，求助一下。

**Comment by feihuamantian** [comment]
git clone https://github.com/Dao-AILab/flash-attention.git

**Comment by feihuamantian** [comment]
flash-atten安装错误，你可以安装以下版本：
git clone https://github.com/Dao-AILab/flash-attention.git    
cd flash-attention
git checkout v2.3.6
python setup.py install

**Comment by feihuamantian** [comment]
想了解更多多模态大模型，可以加微信拉入群：yx116169

**Comment by liutianye** [comment]
已经解决了，重新开新的conda环境解决了。
