### ISSUE TITLE
How to Load the fine tuned model

### ISSUE THREAD

**Issue by RishitLunia3108** [Ucas-HaoranWei/GOT-OCR2.0#98]
!swift sft \
--model_type got-ocr2 \
--model_id_or_path stepfun-ai/GOT-OCR2_0 \
--sft_type lora \
--dataset /kaggle/working/output_data.json \
--output_dir /kaggle/working/hindi_got_model_3 \
--num_train_epochs 1 \
--max_steps 100 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 4 \
--learning_rate 2e-5 \
--lora_rank 8 \
--lora_alpha 32 \
--lora_dropout 0.05 \
--evaluation_strategy steps \
--eval_steps 20 \
--save_strategy steps \
--save_steps 20 

I used this to fine tune the model 
now pls guide how to load it and use it to extract text pls guide

**Comment by Ucas-HaoranWei** [comment]
Hi, inference after fine-tuning：
![image](https://github.com/user-attachments/assets/cb7a77c8-8f89-46fe-ac1b-df8d61d3e777)

**Comment by RishitLunia3108** [comment]
ohk thanks

**Comment by minhduc01168** [comment]
@RishitLunia3108 Have you been able to fine-tune the model on your data set? Can you share with me the process? I am very grateful to you for that.

**Comment by RishitLunia3108** [comment]
sure
pls find the code below

# %%
!pwd
!ls -R

# %%
!git clone https://github.com/modelscope/ms-swift.git
%cd ms-swift

# %%
!pip install -e .[llm]

# %%
%cd ..

# %%
import os

# Set environment variables
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # Kaggle typically provides a single GPU


# %%
! pip install verovio

# %%
import pandas as pd
import json

# Load the CSV data
file_path = '/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/data.csv'
df = pd.read_csv(file_path, encoding='utf-8')


# %%
import os
import json

# Base path for images
image_base_path = '/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/output_images/'

json_data = []

# Loop through the CSV data and create JSON objects
for index, row in df.iterrows():
    # Construct the full image path by combining the base path with the filename
    full_image_path = os.path.join(image_base_path, row['image_file'])
    
    json_obj = {
        "query": "<image>Transcribe the text in this image",  # Fixed query text
        "response": row['text'],                             # Expected output from the CSV
        "images": [full_image_path]                          # Full image path
    }
    json_data.append(json_obj)

# Convert the list of dictionaries to JSON format
json_output = json.dumps(json_data, indent=4, ensure_ascii=False)

# Save to a JSON file (optional)
output_file_path = '/kaggle/working/output_data.json'
with open(output_file_path, 'w', encoding='utf-8') as f:
    f.write(json_output)

print("JSON file created successfully!")


# %%
!swift sft \
--model_type got-ocr2 \
--model_id_or_path stepfun-ai/GOT-OCR2_0 \
--sft_type lora \
--dataset /kaggle/working/output_data.json \
--output_dir /kaggle/working/hindi_got_model_3 \
--num_train_epochs 1 \
--max_steps 1000 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 4 \
--learning_rate 2e-5 \
--lora_rank 8 \
--lora_alpha 32 \
--lora_dropout 0.05 \
--evaluation_strategy steps \
--eval_steps 200 \
--save_strategy steps \
--save_steps 200

# %%
import os
import json

# Base path for images
image_base_path = '/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/TestSamples/'

json_data = []

# Loop through the CSV data and create JSON objects (limit to 10 files)
for index, row in df.iterrows():
    if index >= 10:
        break  # Stop after processing 10 files
    
    # Construct the full image path by combining the base path with the filename
    full_image_path = os.path.join(image_base_path, row['image_file'])
    
    json_obj = {
        "query": "<image>Transcribe the text in this image",  # Fixed query text
        "response": row['text'],                             # Expected output from the CSV
        "images": [full_image_path]                          # Full image path
    }
    json_data.append(json_obj)

# Convert the list of dictionaries to JSON format
json_output = json.dumps(json_data, indent=4, ensure_ascii=False)

# Save to a JSON file (optional)
output_file_path = '/kaggle/working/test1.json'
with open(output_file_path, 'w', encoding='utf-8') as f:
    f.write(json_output)

print("JSON file created successfully!")


# %%
!CUDA_VISIBLE_DEVICES=0 swift infer\
--ckpt_dir /kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000 \
--dataset /kaggle/working/test1.json \
--load_dataset_config true

**Comment by minhduc01168** [comment]
@RishitLunia3108 Can you explain the data format below to me? I'm very grateful for that.
{"query": "55555", "response": "66666", "images": ["image_path"]}
{"query": "eeeee", "response": "fffff", "history": [], "images": ["image_path1", "image_path2"]}
{"query": "EEEEE", "response": "FFFFF", "history": [["query1", "response1"], ["query2", "response2"]]}

**Comment by RishitLunia3108** [comment]
1) so basically this data is used to finetune you GOT-OCR 2.0 model for different languages
2) the query contains the what do you want from the image and what type of data you are giving to the model 
for example here we are give the model an image so the query section for all the json data will contain 
=>  "query": "<image>Transcribe the text in this image"
3) the response contains the expected text which you will be expecting after extracting from the image 
this is done in the case of training , in the case if testing it will be empty as the model will itself fill the response with the extracted text 
**The format of JSON during training**
{
        "query": "<image>Transcribe the text in this image",
        "response": "गर्भनिरोध के लिए महिलाएं क्यों कराती हैं नसबंदी",
        "images": [
            "path_to_image"
        ]
 }
 **The format of JSON during testing**
{
        "query": "<image>Transcribe the text in this image",
        "response": "",
        "images": [
            "path_to_image"
        ]
 }
 
the history is the query and response of the previous image trained 
image_path contains the image path from which u want to extract the text from 
Currently i have not used the history part in my finetunning code

**Comment by thanhhuynhk17** [comment]
> 3\. "response": "गर्भनिरोध के लिए महिलाएं क्यों कराती हैं नसबंदी",

Could you please introduce your tokenization work, or is it just raw text?
I’ve fine-tuned with Vietnamese, but the accuracy is too low.

**Comment by minhduc01168** [comment]
@thanhhuynhk17 Can you tell me what data set you used to fine-tune on Vietnamese? Can you share it with me?

**Comment by thanhhuynhk17** [comment]
Here you are: https://www.kaggle.com/datasets/ducthinhhust/vietocr

It's just a random pick for study purposes

**Comment by RishitLunia3108** [comment]
> > 3. "response": "गर्भनिरोध के लिए महिलाएं क्यों कराती हैं नसबंदी",
> 
> Could you please introduce your tokenization work, or is it just raw text? I’ve fine-tuned with Vietnamese, but the accuracy is too low.

**Comment by RishitLunia3108** [comment]
i did not used a tokenizer it is just raw text
use the kaggle GPU for finetuning 
use more epoch numbers
!swift sft
--model_type got-ocr2
--model_id_or_path stepfun-ai/GOT-OCR2_0
--sft_type lora
--dataset /kaggle/working/output_data.json
--output_dir /kaggle/working/hindi_got_model_3
--num_train_epochs 1
--max_steps 1000
--per_device_train_batch_size 1
--gradient_accumulation_steps 4
--learning_rate 2e-5
--lora_rank 8
--lora_alpha 32
--lora_dropout 0.05
--evaluation_strategy steps
--eval_steps 200
--save_strategy steps
--save_steps 200

here i used 1000 then also the accuracy was around 82 percent 
if u want more accuracy just increase the number of max_steps (around 3500 to 4000)
according to me this will increase your accuracy

**Comment by minhduc01168** [comment]
> i did not used a tokenizer it is just raw text use the kaggle GPU for finetuning use more epoch numbers !swift sft --model_type got-ocr2 --model_id_or_path stepfun-ai/GOT-OCR2_0 --sft_type lora --dataset /kaggle/working/output_data.json --output_dir /kaggle/working/hindi_got_model_3 --num_train_epochs 1 --max_steps 1000 --per_device_train_batch_size 1 --gradient_accumulation_steps 4 --learning_rate 2e-5 --lora_rank 8 --lora_alpha 32 --lora_dropout 0.05 --evaluation_strategy steps --eval_steps 200 --save_strategy steps --save_steps 200
> 
> here i used 1000 then also the accuracy was around 82 percent if u want more accuracy just increase the number of max_steps (around 3500 to 4000) according to me this will increase your accuracy

@RishitLunia3108 Can you share the notebook you run on kaggle and the code structure and json file after creation?
I still can't run the fine-tuning commandCan you share the notebook you run on kaggle and the code structure and json file after creation?
I still can't run the fine-tuning command

**Comment by minhduc01168** [comment]
@RishitLunia3108 
![dataset_got_ocr2 0](https://github.com/user-attachments/assets/f6fb499a-5424-4adf-8d9f-67d63b320b8d)
My file.json dataset structure is as follows but I get an error when loading the dataset. Can you tell me if the above dataset structure is correct? I'm very grateful for that

**Comment by thanhhuynhk17** [comment]
- query must include \"\<image>"
- images is path of image
e.g:
```
[
...,
 {
   "query": "<image>\nOCR:",
   "images": "/kaggle/input/vietnamese-ocr/data_proccessed_img_split/folder_1/page_1.png",
   ...
 },
...,
]
```

**Comment by minhduc01168** [comment]
@thanhhuynhk17 Bạn đã training thành công chưa bạn có thể cho tôi xem file json và cấu trúc dataset của bạn được không? Tôi xin cảm ơn

**Comment by thanhhuynhk17** [comment]
> @thanhhuynhk17 Bạn đã training thành công chưa bạn có thể cho tôi xem file json và cấu trúc dataset của bạn được không? Tôi xin cảm ơn

https://www.kaggle.com/code/tnthnhneee/got-ocr2-0-fine-tuned-vi

**Comment by minhduc01168** [comment]
> > @thanhhuynhk17 Bạn đã training thành công chưa bạn có thể cho tôi xem file json và cấu trúc dataset của bạn được không? Tôi xin cảm ơn
> 
> https://www.kaggle.com/code/tnthnhneee/got-ocr2-0-fine-tuned-vi

Link chưa public thì phải bạn?

**Comment by thanhhuynhk17** [comment]
check lại nha bn

**Comment by minhduc01168** [comment]
> check lại nha bn

![image](https://github.com/user-attachments/assets/df132eaf-ba95-4293-8e25-bec0d176aeaa)
Vẫn private bạn

**Comment by Ucas-HaoranWei** [comment]
Hi, all, I think two points can improve the performance of other languages: 1. Turn off Lora and fine-tune the decoder‘s ’full parameters; 2. Unfreeze the encoder,  change the line132 and 146 'False' to True" https://github.com/Ucas-HaoranWei/GOT-OCR2.0/blob/main/GOT-OCR-2.0-master/GOT/model/GOT_ocr_2_0.py#L132.

**Comment by RishitLunia3108** [comment]
> > i did not used a tokenizer it is just raw text use the kaggle GPU for finetuning use more epoch numbers !swift sft --model_type got-ocr2 --model_id_or_path stepfun-ai/GOT-OCR2_0 --sft_type lora --dataset /kaggle/working/output_data.json --output_dir /kaggle/working/hindi_got_model_3 --num_train_epochs 1 --max_steps 1000 --per_device_train_batch_size 1 --gradient_accumulation_steps 4 --learning_rate 2e-5 --lora_rank 8 --lora_alpha 32 --lora_dropout 0.05 --evaluation_strategy steps --eval_steps 200 --save_strategy steps --save_steps 200
> > here i used 1000 then also the accuracy was around 82 percent if u want more accuracy just increase the number of max_steps (around 3500 to 4000) according to me this will increase your accuracy
> 
> @RishitLunia3108 Can you share the notebook you run on kaggle and the code structure and json file after creation? I still can't run the fine-tuning commandCan you share the notebook you run on kaggle and the code structure and json file after creation? I still can't run the fine-tuning command



here is the full code 

# %%
!pwd
!ls -R

# %%
!git clone https://github.com/modelscope/ms-swift.git
%cd ms-swift

# %%
!pip install -e .[llm]

# %%
%cd ..

# %%
import os

# Set environment variables
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # Kaggle typically provides a single GPU


# %%
! pip install verovio

# %%
import pandas as pd
import json

# Load the CSV data
file_path = '/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/data.csv'
df = pd.read_csv(file_path, encoding='utf-8')


# %%
import os
import json

# Base path for images
image_base_path = '/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/output_images/'

json_data = []

# Loop through the CSV data and create JSON objects
for index, row in df.iterrows():
    # Construct the full image path by combining the base path with the filename
    full_image_path = os.path.join(image_base_path, row['image_file'])
    
    json_obj = {
        "query": "<image>Transcribe the text in this image",  # Fixed query text
        "response": row['text'],                             # Expected output from the CSV
        "images": [full_image_path]                          # Full image path
    }
    json_data.append(json_obj)

# Convert the list of dictionaries to JSON format
json_output = json.dumps(json_data, indent=4, ensure_ascii=False)

# Save to a JSON file (optional)
output_file_path = '/kaggle/working/output_data.json'
with open(output_file_path, 'w', encoding='utf-8') as f:
    f.write(json_output)

print("JSON file created successfully!")


# %%
!swift sft \
--model_type got-ocr2 \
--model_id_or_path stepfun-ai/GOT-OCR2_0 \
--sft_type lora \
--dataset /kaggle/working/output_data.json \
--output_dir /kaggle/working/hindi_got_model_3 \
--num_train_epochs 1 \
--max_steps 1000 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 4 \
--learning_rate 2e-5 \
--lora_rank 8 \
--lora_alpha 32 \
--lora_dropout 0.05 \
--evaluation_strategy steps \
--eval_steps 200 \
--save_strategy steps \
--save_steps 200

# %%
import os
import json

# Base path for images
image_base_path = '/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/TestSamples/'

json_data = []

# Loop through the CSV data and create JSON objects (limit to 10 files)
for index, row in df.iterrows():
    if index >= 10:
        break  # Stop after processing 10 files
    
    # Construct the full image path by combining the base path with the filename
    full_image_path = os.path.join(image_base_path, row['image_file'])
    
    json_obj = {
        "query": "<image>Transcribe the text in this image",  # Fixed query text
        "response": row['text'],                             # Expected output from the CSV
        "images": [full_image_path]                          # Full image path
    }
    json_data.append(json_obj)

# Convert the list of dictionaries to JSON format
json_output = json.dumps(json_data, indent=4, ensure_ascii=False)

# Save to a JSON file (optional)
output_file_path = '/kaggle/working/test1.json'
with open(output_file_path, 'w', encoding='utf-8') as f:
    f.write(json_output)

print("JSON file created successfully!")


# %%
!CUDA_VISIBLE_DEVICES=0 swift infer\
--ckpt_dir /kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000 \
--dataset /kaggle/working/test1.json \
--load_dataset_config true 

# %%
import os

# Define the path to the checkpoint
checkpoint_path = "/kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000"

# Create a zip file name
zip_name = "checkpoint-1000.zip"

# Create the zip file
!zip -r /kaggle/working/{zip_name} {checkpoint_path}

print(f"Zip file created: /kaggle/working/{zip_name}")



this is the format for the training purpose
[
    {
        "query": "<image>Transcribe the text in this image",
        "response": "गर्भनिरोध के लिए महिलाएं क्यों कराती हैं नसबंदी",
        "images": [
            "/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/TestSamples/1.png"
        ]
    },
    {
        "query": "<image>Transcribe the text in this image",
        "response": "'मस्‍ज‍िद ख़ुदा का घर है तो यह ईमान वाली स्‍त्र‍ियों के लिए कैसे बंद हो सकता है'",
        "images": [
            "/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/TestSamples/2.png"
        ]
    },
    {
        "query": "<image>Transcribe the text in this image",
        "response": "नज़रिया: गोरखपुर, नागपुर और दिल्ली के त्रिकोण में फंसा है 2019",
        "images": [
            "/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/TestSamples/3.png"
        ]
    },
    {
        "query": "<image>Transcribe the text in this image",
        "response": "अनुच्छेद 370 के बाद क्या हो सकता है मोदी सरकार का अगला कदम?",
        "images": [
            "/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/TestSamples/4.png"
        ]
    },
    {
        "query": "<image>Transcribe the text in this image",
        "response": "इराक़ में तीन अमरीकी सैनिक मारे गए",
        "images": [
            "/kaggle/input/hindi-ocr-synthetic-line-image-text-pair/data_80k/TestSamples/5.png"
        ]
    },
]

**Comment by ShubhamPatel2305** [comment]
Thank you so much man these are helping me a lot.

**Comment by RishitLunia3108** [comment]
https://github.com/RishitLunia3108/Fine_Tuning_GOT_OCR_2.0_For_Hindi_Languge_Extraction.git

This is my GitHub repo link where the fine tuning is done for hindi language

**Comment by minhduc01168** [comment]
> Hi, all, I think two points can improve the performance of other languages: 1. Turn off Lora and fine-tune the decoder‘s ’full parameters; 2. Unfreeze the encoder, change the line132 and 146 'False' to True" https://github.com/Ucas-HaoranWei/GOT-OCR2.0/blob/main/GOT-OCR-2.0-master/GOT/model/GOT_ocr_2_0.py#L132.
@Ucas-HaoranWei Can you tell me how can I do these 2 things when I fine-tuning. Because I followed the Fine-tune section in README.md, the loss was quite high. 
My training command:
CUDA_VISIBLE_DEVICES=0.1 
!swift sft \
--model_type got-ocr2\
--model_id_or_path stepfun-ai/GOT-OCR2_0 \
--sft_type lora \
--dataset /kaggle/input/vietnamese-ocr-trang-a4/vietnamese_ocr_A4/train/train_data.json \
--output_dir /kaggle/working/vietnamese_ocr_a4_got_model_3 \
--num_train_epochs 1 \
--max_steps 1000 \
--per_device_train_batch_size 2 \
--gradient_accumulation_steps 4 \
--learning_rate 2e-5 \
--lora_rank 8 \
--lora_alpha 32 \
--lora_dropout 0.05 \
--evaluation_strategy steps \
--eval_steps 200 \
--save_strategy steps \
--save_steps 200

**Comment by evanlin88** [comment]
> https://github.com/RishitLunia3108/Fine_Tuning_GOT_OCR_2.0_For_Hindi_Languge_Extraction.git
> 
> This is my GitHub repo link where the fine tuning is done for hindi language

Well Done！ And Do you know how to use "from peft import PeftModel" to start up the model?
The code like this:
model_name = '/local/got-ocr2-model'
lora_model_path =  '/kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000'
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)

model = PeftModel.from_pretrained(model, lora_model_path)
# and will throw exception :
Traceback (most recent call last):
File "/local/GOT-OCR2.0-main/GOT-OCR-2.0-master/GOT/demo/run_ocr_server.py", line 48, in
model = PeftModel.from_pretrained(model, lora_model_path)
File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 270, in from_pretrained
model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 893, in init
super().init(model, peft_config, adapter_name)
File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 112, in init
self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 180, in init
self.add_adapter(adapter_name, self.peft_config[adapter_name])
File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 194, in add_adapter
self._find_and_replace(adapter_name)
File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 352, in _find_and_replace
new_module = self._create_new_module(lora_config, adapter_name, target)
File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 305, in _create_new_module
raise ValueError(
ValueError: Target module ModuleList(
(0-23): 24 x Qwen2DecoderLayer(
(self_attn): Qwen2SdpaAttention(
(q_proj): Linear(in_features=1024, out_features=1024, bias=True)
(k_proj): Linear(in_features=1024, out_features=1024, bias=True)
(v_proj): Linear(in_features=1024, out_features=1024, bias=True)
(o_proj): Linear(in_features=1024, out_features=1024, bias=False)
(rotary_emb): Qwen2RotaryEmbedding()
)
(mlp): Qwen2MLP(
(gate_proj): Linear(in_features=1024, out_features=2816, bias=False)
(up_proj): Linear(in_features=1024, out_features=2816, bias=False)
(down_proj): Linear(in_features=2816, out_features=1024, bias=False)
(act_fn): SiLU()
)
(input_layernorm): Qwen2RMSNorm()
(post_attention_layernorm): Qwen2RMSNorm()
)
) is not supported. Currently, only torch.nn.Linear and Conv1D are supported.

# Do you know how to fix it? thks

**Comment by RishitLunia3108** [comment]
> > https://github.com/RishitLunia3108/Fine_Tuning_GOT_OCR_2.0_For_Hindi_Languge_Extraction.git
> > This is my GitHub repo link where the fine tuning is done for hindi language
> 
> @RishitLunia3108 Well Done！ And Do you know how to use "from peft import PeftModel" to start up the model after fine-tuning? The code like this:
> 
> model_name = '/local/got-ocr2-model' lora_model_path = '/kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000' tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True) model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)
> 
> model = PeftModel.from_pretrained(model, lora_model_path)
> 
> # and will throw exception :
> Traceback (most recent call last): File "/local/GOT-OCR2.0-main/GOT-OCR-2.0-master/GOT/demo/run_ocr_server.py", line 48, in model = PeftModel.from_pretrained(model, lora_model_path) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 270, in from_pretrained model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 893, in init super().init(model, peft_config, adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 112, in init self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type]( File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 180, in init self.add_adapter(adapter_name, self.peft_config[adapter_name]) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 194, in add_adapter self._find_and_replace(adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 352, in _find_and_replace new_module = self._create_new_module(lora_config, adapter_name, target) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 305, in _create_new_module raise ValueError( ValueError: Target module ModuleList( (0-23): 24 x Qwen2DecoderLayer( (self_attn): Qwen2SdpaAttention( (q_proj): Linear(in_features=1024, out_features=1024, bias=True) (k_proj): Linear(in_features=1024, out_features=1024, bias=True) (v_proj): Linear(in_features=1024, out_features=1024, bias=True) (o_proj): Linear(in_features=1024, out_features=1024, bias=False) (rotary_emb): Qwen2RotaryEmbedding() ) (mlp): Qwen2MLP( (gate_proj): Linear(in_features=1024, out_features=2816, bias=False) (up_proj): Linear(in_features=1024, out_features=2816, bias=False) (down_proj): Linear(in_features=2816, out_features=1024, bias=False) (act_fn): SiLU() ) (input_layernorm): Qwen2RMSNorm() (post_attention_layernorm): Qwen2RMSNorm() ) ) is not supported. Currently, only torch.nn.Linear and Conv1D are supported.
> 
> # Do you know how to fix it? thks
> -- btw ... I had fixed it

Hey @evanlin88 
Never used this from peft import PeftModel , I will look into it and will get back to you

**Comment by rahulverma7788** [comment]
> > https://github.com/RishitLunia3108/Fine_Tuning_GOT_OCR_2.0_For_Hindi_Languge_Extraction.git
> > This is my GitHub repo link where the fine tuning is done for hindi language
> 
> @RishitLunia3108 Well Done！ And Do you know how to use "from peft import PeftModel" to start up the model after fine-tuning? The code like this:
> 
> model_name = '/local/got-ocr2-model' lora_model_path = '/kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000' tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True) model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)
> 
> model = PeftModel.from_pretrained(model, lora_model_path)
> 
> # and will throw exception :
> Traceback (most recent call last): File "/local/GOT-OCR2.0-main/GOT-OCR-2.0-master/GOT/demo/run_ocr_server.py", line 48, in model = PeftModel.from_pretrained(model, lora_model_path) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 270, in from_pretrained model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 893, in init super().init(model, peft_config, adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 112, in init self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type]( File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 180, in init self.add_adapter(adapter_name, self.peft_config[adapter_name]) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 194, in add_adapter self._find_and_replace(adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 352, in _find_and_replace new_module = self._create_new_module(lora_config, adapter_name, target) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 305, in _create_new_module raise ValueError( ValueError: Target module ModuleList( (0-23): 24 x Qwen2DecoderLayer( (self_attn): Qwen2SdpaAttention( (q_proj): Linear(in_features=1024, out_features=1024, bias=True) (k_proj): Linear(in_features=1024, out_features=1024, bias=True) (v_proj): Linear(in_features=1024, out_features=1024, bias=True) (o_proj): Linear(in_features=1024, out_features=1024, bias=False) (rotary_emb): Qwen2RotaryEmbedding() ) (mlp): Qwen2MLP( (gate_proj): Linear(in_features=1024, out_features=2816, bias=False) (up_proj): Linear(in_features=1024, out_features=2816, bias=False) (down_proj): Linear(in_features=2816, out_features=1024, bias=False) (act_fn): SiLU() ) (input_layernorm): Qwen2RMSNorm() (post_attention_layernorm): Qwen2RMSNorm() ) ) is not supported. Currently, only torch.nn.Linear and Conv1D are supported.
> 
> # Do you know how to fix it? thks
> -- btw ... I had fixed it

Can you tell me how can load model after fine tuning?

**Comment by RishitLunia3108** [comment]
> > > https://github.com/RishitLunia3108/Fine_Tuning_GOT_OCR_2.0_For_Hindi_Languge_Extraction.git
> > > This is my GitHub repo link where the fine tuning is done for hindi language
> > 
> > 
> > @RishitLunia3108 Well Done！ And Do you know how to use "from peft import PeftModel" to start up the model after fine-tuning? The code like this:
> > model_name = '/local/got-ocr2-model' lora_model_path = '/kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000' tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True) model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)
> > model = PeftModel.from_pretrained(model, lora_model_path)
> > # and will throw exception :
> > Traceback (most recent call last): File "/local/GOT-OCR2.0-main/GOT-OCR-2.0-master/GOT/demo/run_ocr_server.py", line 48, in model = PeftModel.from_pretrained(model, lora_model_path) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 270, in from_pretrained model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 893, in init super().init(model, peft_config, adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 112, in init self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type]( File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 180, in init self.add_adapter(adapter_name, self.peft_config[adapter_name]) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 194, in add_adapter self._find_and_replace(adapter_name) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 352, in _find_and_replace new_module = self._create_new_module(lora_config, adapter_name, target) File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 305, in _create_new_module raise ValueError( ValueError: Target module ModuleList( (0-23): 24 x Qwen2DecoderLayer( (self_attn): Qwen2SdpaAttention( (q_proj): Linear(in_features=1024, out_features=1024, bias=True) (k_proj): Linear(in_features=1024, out_features=1024, bias=True) (v_proj): Linear(in_features=1024, out_features=1024, bias=True) (o_proj): Linear(in_features=1024, out_features=1024, bias=False) (rotary_emb): Qwen2RotaryEmbedding() ) (mlp): Qwen2MLP( (gate_proj): Linear(in_features=1024, out_features=2816, bias=False) (up_proj): Linear(in_features=1024, out_features=2816, bias=False) (down_proj): Linear(in_features=2816, out_features=1024, bias=False) (act_fn): SiLU() ) (input_layernorm): Qwen2RMSNorm() (post_attention_layernorm): Qwen2RMSNorm() ) ) is not supported. Currently, only torch.nn.Linear and Conv1D are supported.
> > # Do you know how to fix it? thks
> > -- btw ... I had fixed it
> 
> Can you tell me how can load model after fine tuning?


!CUDA_VISIBLE_DEVICES=0 swift infer
--ckpt_dir /kaggle/working/hindi_got_model_3/got-ocr2/v0-20240930-060444/checkpoint-1000
--dataset /kaggle/working/test1.json
--load_dataset_config true

the above code is used to load the model and test it on the data to get the output after finetunning of the model

**Comment by PranjalSrivastava361** [comment]
I always getting this - AttributeError: 'NoneType' object has no attribute 'supports_gradient_checkpointing'  while running training training code ...if anyone can help please!
